# Generated by Django 4.2.16 on 2024-11-23 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='last name'),
        ),
        migrations.CreateModel(
            name='JWTTokenBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=500, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('refresh_tokens', models.CharField(max_length=500, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='black_listed_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JwtTokenBlacklist',
                'verbose_name_plural': 'JwtTokenBlacklists',
            },
        ),
    ]
