# Generated by Django 4.2.16 on 2024-11-28 12:16

import accounts.models
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ('user',), 'verbose_name': 'User Address', 'verbose_name_plural': 'User addresses'},
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_village', to='accounts.village'),
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('high_res', models.ImageField(upload_to=accounts.models.ProfilePicture.get_original_image_upload_path)),
                ('medium_res', models.ImageField(blank=True, null=True, upload_to=accounts.models.ProfilePicture.get_medium_quality_upload_path)),
                ('low_res', models.ImageField(blank=True, null=True, upload_to=accounts.models.ProfilePicture.get_low_quality_upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Picture',
                'verbose_name_plural': 'Profile Pictures',
            },
        ),
    ]
