# Generated by Django 4.2.16 on 2024-11-29 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_useraddress_options_useraddress_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=6, null=True)),
                ('status', models.BooleanField(default=False)),
                ('label', models.CharField(choices=[('SIGNUP', 'Signup'), ('RESET_PASSWORD', 'Reset password'), ('CHANGE_EMAIL', 'Change email')], default='CHANGE_EMAIL', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('code', 'user')},
            },
        ),
    ]
